name: build and deploy to github pages

on:
  push:
    branches:
      - source

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the site source
        uses: actions/checkout@master

      - name: build the site
        uses: docker://nmhnmh/sitekicker@latest
        with:
          args: ${{ GITHUB_WORKSPACE }}

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v2.2.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ${{ GITHUB_WORKSPACE }}/.build
